<a href="https://colab.research.google.com/github/shagun00151/Natural-Language-processing/blob/main/WordEmbTechniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  error: subprocess-exited-with-error
  
  × Running setup.py install for tensorflow-gpu did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for tensorflow-gpu ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tensorflow-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for outpu

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.11.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# sentences
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## vocabulary size
voc_size = 10000
# your word indexing will be on the basis of 0-10000
# vocabulary size is an hyperparameter concept.

In [9]:
## One hot representation
onehot_repr = [one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[394, 1334, 3163, 2769], [394, 1334, 3163, 655], [394, 460, 3163, 9208], [6488, 3327, 2408, 6996, 5738], [6488, 3327, 2408, 6996, 3231], [1189, 394, 3820, 3163, 2916], [5135, 2887, 756, 6996]]


In [10]:
## WORD EMBEDDINGS REPRESENTATION

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

Sequential is used to make sequential neural network.

In [12]:
import numpy as np

To remove the irregularity of the **sentences** and total words of each sentences will be 8 instead of 4,4,5 or 6.

In [13]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
# if we use post padding in it then zeros will be added at last of it.

[[   0    0    0    0  394 1334 3163 2769]
 [   0    0    0    0  394 1334 3163  655]
 [   0    0    0    0  394  460 3163 9208]
 [   0    0    0 6488 3327 2408 6996 5738]
 [   0    0    0 6488 3327 2408 6996 3231]
 [   0    0    0 1189  394 3820 3163 2916]
 [   0    0    0    0 5135 2887  756 6996]]


In [14]:
dim = 10

In [15]:
model = Sequential()

In [16]:
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 205ms/step
[[[-0.04094691 -0.00209328 -0.03047901 -0.03375046 -0.00066106
    0.03532714 -0.03548086 -0.03707945  0.00679304 -0.03024639]
  [-0.04094691 -0.00209328 -0.03047901 -0.03375046 -0.00066106
    0.03532714 -0.03548086 -0.03707945  0.00679304 -0.03024639]
  [-0.04094691 -0.00209328 -0.03047901 -0.03375046 -0.00066106
    0.03532714 -0.03548086 -0.03707945  0.00679304 -0.03024639]
  [-0.04094691 -0.00209328 -0.03047901 -0.03375046 -0.00066106
    0.03532714 -0.03548086 -0.03707945  0.00679304 -0.03024639]
  [ 0.03242021  0.03095933  0.01243879  0.0174659  -0.0041251
   -0.0242137   0.00383852  0.01998873 -0.04857939 -0.04366657]
  [-0.0446892   0.01575695  0.03245834  0.03516755 -0.02477717
    0.01313641  0.03656801 -0.02373437  0.02383473 -0.02673056]
  [-0.03347973  0.04629921 -0.04164935 -0.00657924  0.04840363
   -0.01843208 -0.03150578 -0.01092448 -0.04722684 -0.024786  ]
  [ 0.02293015  0.01575952 -0.01852841 -0.00612431  0.00510

In [19]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0,  394, 1334, 3163, 2769], dtype=int32)